#!/bin/sh

main() {
        file="$(mktemp)"
        fib "$1" > "$file"
        if grep "e" "$file" 2>/dev/null 1>&2; then
                printf '~'
                echo "$(fib "$1")" | calc
        else
                fib "$1"
        fi
        rm -f "$file" 2>/dev/null 1>&2
}

main "$@"
