#!/bin/sh
set -e
# set -x

checkDirs() {
        if ! test -d "$HOME"/.config/passwds; then
                mkdir -p "$HOME"/.config/passwds && echo "Created ${HOME}/.config/passwds for the first time"
        fi

        if ! test -d /tmp/gpgpass; then
                mkdir /tmp/gpgpass
        fi
}

printHelp() {
        echo "Usage: $0 <option>"
        echo "Options:"
        printf "\t-h\t\tPrint this menu\n"
        printf "\t-c\t\tDecrypt password file and copy to clipboard\n"
        printf "\t-n\t\tCreate a new password\n"
        printf "\t-r\t\tRemove an existent password\n"
}

newPassword() {
        printf "\033[0;32mEnter new filename:\033[0m\n"
        read -r name

        printf "\033[0;32mEnter password:\033[0m\n"
        read -r password

        ls "$HOME"/.config/passwds/"$name" 2>/dev/null 1>&2 || cd "$HOME"/.config/passwds
        echo "$password" > "$name"
        gpg -c --no-symkey-cache --cipher-algo AES256 "$name" && rm "$name"
        cd - 2>/dev/null 1>&2 || exit 1
        exit 0
}

removePassword() {
        printf "\033[0;31mEnter filename to remove (no extension)\033[0m\n"
        read -r del_name
        if test -e "$HOME"/.config/passwds/"$del_name".gpg; then
                printf "\033[0;31m%s\033[0m\n" "$(rm -iv "$HOME"/.config/passwds/"$del_name".gpg)"
        else
                echo "Error: file \"$del_name\" not found"
                exit 1
        fi
}

copyPassword() {
        cd "$HOME"/.config/passwds
        fileChosen=$(find -- *.gpg | dmenu -p "Select file: " -l 10)
        if test -z "$fileChosen"; then
                echo "Error: File not found"
                exit 1
        fi

        passfile=$(date +%Y.%m.%d.%M.%S)
        gpg -o /tmp/gpgpass/"$passfile" -d "$HOME"/.config/passwds/"$fileChosen" 2>/dev/null 1>&2

        if test -r /tmp/gpgpass/"$passfile"; then
                xclip -r -selection clipboard < /tmp/gpgpass/"$passfile" && echo "Copied $fileChosen contents to clipboard"
                rm "/tmp/gpgpass/$passfile"
                exit 0

        else
                echo "Error: Failed to copy password to clipboard"
                exit 1
        fi
}

copyPasswordFile() {
        fileChosen="$1.gpg"

        if test -z "$fileChosen"; then
                echo "Error: File not found"
                exit 1
        fi

        passfile=$(date +%Y.%m.%d.%M.%S)
        gpg -o /tmp/gpgpass/"$passfile" -d "$HOME"/.config/passwds/"$fileChosen" 2>/dev/null 1>&2

        if test -r /tmp/gpgpass/"$passfile"; then
                xclip -r -selection clipboard < /tmp/gpgpass/"$passfile" && echo "Copied $fileChosen contents to clipboard"
                rm "/tmp/gpgpass/$passfile"
                exit 0

        else
                echo "Error: Failed to copy password to clipboard"
                exit 1
        fi
}

listPasswords() {
        cd "$HOME"/.config/passwds
        find -- *
        cd - 2>/dev/null 1>&2 || exit 1
        exit 0
}

checkOption() {
        if test -n "$1"; then
                if test "$1" = "-h"; then
                        printHelp
                        exit 0

                elif test "$1" = "-n"; then
                        newPassword
                        exit 0

                elif test "$1" = "-r"; then
                        removePassword
                        exit 0
                elif test "$1" = "-c"; then
                        copyPasswordFile "$2"
                        exit 0
                elif test "$1" = "-l"; then
                        listPasswords
                        exit 0
                fi
        else
                copyPassword
                exit 1

        fi
}

main() {
        checkDirs
        checkOption "$@"
        exit 0
}

main "$@"
