#!/bin/sh

displayDrives() {
        lsblk
}

selectDrive() {
        select drive_id in $(lsblk | grep part | cut -c3,4,5,6)
        do
                echo "$drive_id selected"
                break
        done
}

getDriveId() {
        drive_id=$(lsblk | grep 1.8 | grep part | cut -c3,4,5,6)
}

recover() {
        (doas e2fsck -p /dev/"$1" && echo "Done recovering /dev/$1") || exit 1
}

mountIt() {
        doas mount /dev/"$1" /mnt && echo "Mounted /dev/$1 to /mnt"
}

checkOptions() {
        if test -z "$1"; then
                getDriveId
                recover "$drive_id"
                mountIt "$drive_id"

        elif test "$1" = "-s"; then
                displayDrives
                selectDrive
                mountIt "$drive_id"
        else
                exit 1
        fi

}

main() {
        checkOptions "$@"
        exit 0
}

main "$@"
