#!/bin/sh


if test -n "$1"; then
        play="https://twitch.tv/"
        play+="$1"
        devour mpv "$play"

elif test -z "$1"; then
        result=$(dmenu -l 10 -p "Choose a streamer: " < ~/.config/mpvtwitch/channels.txt)
        devour mpv "$result"

else
        exit 1
fi
