#!/bin/sh

createScript() {
        touch "$HOME/.local/scripts/$1" || exit 1
}

makeExec() {
        chmod +x "$HOME/.local/scripts/$1" || exit 1
}

openScript() {
        vi "$HOME/.local/scripts/$1" || exit 1
}

checkOptions() {
        if test -n "$1"; then
                createScript "$1"
                makeExec "$1"
                openScript "$1"
        else
                exit 1
        fi
}

main() {
        checkOptions "$@"
}       

main "$@"
