#!/bin/sh

set -xe

createLocalScript() {
        touch ~/repos/github.com/anon/scripts/"$1" || exit 1
}

createRelativeScript() {
        touch "$1"
}

makeRelativeExec() {
        chmod +x "$1"
}

makeLocalExec() {
        chmod +x ~/repos/github.com/anon/scripts/"$1" || exit 1
}

openLocalScript() {
        vi ~/repos/github.com/anon/scripts/"$1" || exit 1
}

openScript() {
        vi "$1"
}

checkOptions() {
        if test -n "$1" && test "$1" != "-n"; then
                createLocalScript "$1"
                makeLocalExec "$1"
                openLocalScript "$1"
        elif test "$1" = "-n"; then
                createRelativeScript "$2"
                makeRelativeExec "$2"
                openScript "$2"
                
                
        fi
}

main() {
        checkOptions "$@"
}       

main "$@"
