#!/bin/bash -x 

INRES="1680x1050"
OUTRES="1680x1050"
FPS="30"
AC="1"            # switch to 2 for micro
FORMAT="mp4"

ffmpeg -f x11grab -s "$INRES" -r "$FPS" -i :0.0 -f alsa -ac "$AC" \
        -i default -vcodec libx264 -s "$OUTRES" \
        -acodec libmp3lame -ab 128k -ar 44100 \
        -threads 0 -f "$FORMAT" $1
